### ISSUE TITLE
Handle media deletions / 404's

### ISSUE THREAD

**Issue by FujiMakoto** [FujiMakoto/twitter-saucenao#23]
It's possible a tweet may be deleted while we are trying to process it, possibly in the midst of being rate limited.

This results in the image no longer existing and us trying to send an empty upload to SauceNao,
```
You need an Image! <a href="/index.php">...GO BACK TO START...</a> <br /><br /><br /><br />If an image was provided, it may not be loading properly, or may not be in an acceptable format... The image must be: gif, jpg, png, bmp, svg, or webp... <br /> Try another, or convert your image first.<br /><br />Detected Type 1: inode/x-empty<br />Detected Type 2:
[2020-07-23 12:46:17] ERROR: [saucenaopls] SauceNao exception raised: You need an Image! <a href="/index.php">...GO BACK TO START...</a> <br /><br /><br /><br />If an image was provided, it may not be loading properly, or may not be in an acceptable format... The image must be: gif, jpg, png, bmp, svg, or webp... <br /> Try another, or convert your image first.<br /><br />Detected Type 1: inode/x-empty<br />Detected Type 2:
[2020-07-23 12:46:17] ERROR: [saucenaopls] An unknown error occurred while processing tweet 1286387167858655233
Traceback (most recent call last):
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 246, in get_sauce
    sauce = await self.sauce.from_file(path)
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/pysaucenao/saucenao.py", line 78, in from_file
    self._verify_request(status_code, response)
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/pysaucenao/saucenao.py", line 133, in _verify_request
    raise InvalidImageException(header.get('message'))
pysaucenao.errors.InvalidImageException: You need an Image! <a href="/index.php">...GO BACK TO START...</a> <br /><br /><br /><br />If an image was provided, it may not be loading properly, or may not be in an acceptable format... The image must be: gif, jpg, png, bmp, svg, or webp... <br /> Try another, or convert your image first.<br /><br />Detected Type 1: inode/x-empty<br />Detected Type 2:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 91, in check_mentions
    sauce_cache = await self.get_sauce(media_cache, log_index=self.my.screen_name)
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 262, in get_sauce
    sauce_cache = TweetSauceCache.filter_and_set(tweet_cache, index_no=index_no, trigger=trigger)
TypeError: filter_and_set() missing 1 required positional argument: 'sauce_results'
```
So, we need to fix this and add a check when `download_files` is enabled.

**Comment by FujiMakoto** [comment]
Resolved in the following commit
https://github.com/FujiMakoto/twitter-saucenao/commit/264dc9fd9310ebb91259855b6f2e128733b705d0
