### ISSUE TITLE
Handle twitter tweet length errors (186)

### ISSUE THREAD

**Issue by FujiMakoto** [FujiMakoto/twitter-saucenao#6]
We need to implement some way to handle 186 errors (Tweet too long).

This happens rarely, but it does happen. Ideally we should find some way to dynamically shorten tweets when it happens.

```
[2020-07-01 02:00:58] ERROR: [NurseShizuka] An unknown error occurred while processing tweet 1278252003219529728
Traceback (most recent call last):
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 175, in check_monitored
    self.send_reply(tweet, sauce, False)
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 363, in send_reply
    reply = api.update_status(reply, in_reply_to_status_id=tweet.id, auto_populate_reply_metadata=True)
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/tweepy/api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/tweepy/binder.py", line 250, in _call
    return method.execute()
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/tweepy/binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 186, 'message': 'Tweet needs to be a bit shorter.'}]
```

**Comment by FujiMakoto** [comment]
The previous commit helps, but this can still occur when we are being mentioned for specific H-Misc and such entries, notably ones with many artists and really long titles.

**Comment by FujiMakoto** [comment]
This should be mostly resolved now, but if it reoccurs I'll have the issue re-opened.
