### ISSUE TITLE
Non-zero status code returned: 2 / TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by FujiMakoto** [FujiMakoto/twitter-saucenao#9]
Possibly a pygelbooru library issue that we need to look into,

```
Non-zero status code returned: 2
[2020-07-05 02:54:05] ERROR: [saucenaopls] An unknown error occurred while processing tweet 1279715108285853698
Traceback (most recent call last):
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 98, in check_mentions
    sauce = await self.get_sauce(tweet_parser.media[0])
  File "/home/saucenao/twitter-saucenao/twsaucenao/server.py", line 265, in get_sauce
    sauce = await self.sauce.from_url(media)
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/pysaucenao/saucenao.py", line 54, in from_url
    return SauceNaoResults(response, self._min_similarity)
  File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/pysaucenao/containers.py", line 65, in __init__
    for result in results:
TypeError: 'NoneType' object is not iterable
```

**Comment by FujiMakoto** [comment]
This should be addressed with #17
